version: '3.1'

services:
  postgres:
    image: postgres:10
    container_name: bookmark_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bookmark
    networks:
      - newnetwork
      

networks:
  newnetwork:
